language: java

sudo: required

services:
  - docker

jdk:
  - openjdk8
  - oraclejdk11
  - openjdk-ea

script:
  - mvn clean verify

jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      script: mvn clean source:jar javadoc:javadoc deploy -DskipTests --settings travis_settings.xml
      if: branch IN (master, 1.0-STABLE) AND type IN (push) AND repo = bootique/bootique-rabbitmq-client
